---
- hosts: all
  become: yes

  roles:
    - time-lon
    - openstack-conf
    - ceph-mount
    # TODO - glusterfs-mount
    - keystone-users
    - monasca_agent
    - docker
    - prometheus-docker-node
