---
- name: Download spark-bench
  get_url:
    url: https://github.com/SparkTC/spark-bench/releases/download/v55/spark-bench_2.1.1_0.2.2-RELEASE_55.tgz
    dest: /opt/spark/spark-bench_2.1.1_0.2.2-RELEASE.tar.gz

- name: Extract spark-bench
  unarchive:
    src: /opt/spark/spark-bench_2.1.1_0.2.2-RELEASE.tar.gz
    dest: /opt/spark
    remote_src: yes

- name: Run spark-bench example
  shell: |
    export SPARK_HOME=/opt/spark
    export SPARK_MASTER_HOST=spark://{{ ansible_host }}:7077

    export SB_HOME=/opt/spark/spark-bench_2.1.1_0.2.2-RELEASE
    $SB_HOME/bin/spark-bench.sh $SB_HOME/examples/minimal-example.conf

- name: Add generate conf
  template:
    src: generate-files.conf
    dest: /opt/spark/spark-bench_2.1.1_0.2.2-RELEASE/examples/generate-files.conf

- name: Add kmeans run conf
  template:
    src: kmeans.conf
    dest: /opt/spark/spark-bench_2.1.1_0.2.2-RELEASE/examples/kmeans.conf

- name: Generate kmeans files
  shell: |
    export SPARK_HOME=/opt/spark
    export SPARK_MASTER_HOST=spark://{{ ansible_host }}:7077

    export SB_HOME=/opt/spark/spark-bench_2.1.1_0.2.2-RELEASE
    $SB_HOME/bin/spark-bench.sh $SB_HOME/examples/generate-files.conf
  args:
    creates: /home/hadoop/kmeans-medium

- name: Copy kmeans files to slave
  command: "su hadoop -c \"rsync -r /home/hadoop/kmeans-medium hadoop@{{ item }}:/home/hadoop/\""
  with_items: "{{ groups['slave'] }}"

- name: Wait to help post test graphs
  pause:
    seconds: 10

- stat:
    path: /tmp/kmeans-medium-run
  register: check_kmeans

- prompt:
    msg: "If you want to run kmeans benchmark, delete /tmp/kmeans-medium-run"
  when: check_kmeans.stat.exists == True

- name: Run kmeans benchmark
  shell: |
    export SPARK_HOME=/opt/spark
    export SPARK_MASTER_HOST=spark://{{ ansible_host }}:7077

    export SB_HOME=/opt/spark/spark-bench_2.1.1_0.2.2-RELEASE
    $SB_HOME/bin/spark-bench.sh $SB_HOME/examples/kmeans.conf
  args:
    creates: /tmp/kmeans-medium-run
