---
- name: Allow access to centos user
  lineinfile:
    path: /home/centos/.ssh/authorized_keys
    line: "{{ item }}"
    owner: centos
    group: centos
    mode: 0600
  with_items: "{{ hibd_spark_allowed_ssh_keys }}"

- name: Add slaves config
  template:
    src: slaves
    dest: "{{ hibd_spark_home }}/conf/slaves"

- name: Add spark-env
  template:
    src: spark-env.sh
    dest: "{{ hibd_spark_home }}/conf/spark-env.sh"

- name: Add spark-defaults
  template:
    src: spark-defaults.conf
    dest: "{{ hibd_spark_home }}/conf/spark-defaults.conf"

- name: Install python3
  package:
    name: python34-pip

- name: Stop all spark processes
  command: "su hadoop {{ hibd_spark_home }}/sbin/stop-all.sh"
  ignore_errors: true
  when: 'master' in group_names

- name: Start all spark processes
  command: "su hadoop {{ hibd_spark_home }}/sbin/start-all.sh"
  when: 'master' in group_names
