---
- name: Install glusterfs packages for mount and unmount
  yum: name=epel-release,glusterfs-client,glusterfs-rdma,glusterfs-fuse
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: Update hosts file for glusterfs bricks
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ gluster_bricks }}"

- name: Ensure mount directory exists
  file:
    path: /root/mnt
    state: directory
    mode: 0755

- name: Mount Glusterfs
  mount:
    path: /root/mnt
    src: "{{ glusterfs_host }}:{{ glusterfs_path }}"
    fstype: glusterfs
    state: mounted

