---
- name: Install glusterfs packages for mount and unmount
  yum: name=epel-release,glusterfs-client,glusterfs-rdma,glusterfs-fuse
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: Update hosts file for glusterfs bricks
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ gluster_bricks }}"

- name: Ensure mount directory exists
  file:
    path: "{{ glusterfs_mount_path }}"
    state: directory
    mode: 0755

- name: Ensure ib interface is configured (TODO big hack)
  shell: |
    ipx=`/sbin/ifconfig eno1 | grep 'inet ' | cut -d: -f2 | awk '{ print $2}' | cut -d. -f4`
    echo $ipx
    ibdomain=10.60.100
    ifconfig ib0 $ibdomain.$ipx/24

- name: Mount Glusterfs
  mount:
    path: "{{ glusterfs_mount_path }}"
    src: "{{ glusterfs_host }}:{{ glusterfs_path }}"
    fstype: glusterfs
    state: mounted
