---
- vars:
    prometheus_home: /home/centos/prometheus

- name: Create prometheus data dir
  file:
    path: "{{ prometheus_home }}/data"
    state: directory
    mode: 0755

- name: Configure prometheus targets
  template:
    src: prometheus.yml  # TODO - add ip addresses properly
    dest: "{{ prometheus_home }}/prometheus.yml"

- name: Configure prometheus alerts
  template:
    src: alerts.rules
    dest: "{{ prometheus_home }}/alerts.rules"

- name: Add Prometheus server
  docker_container:
    name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - "{{ prometheus_home }}/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "{{ prometheus_home }}/alerts.rules:/etc/prometheus/alerts.rules"
      - "{{ prometheus_home }}/data:/prometheus prom/prometheus"

- name: Create Grafana dir
  file:
    path: "{{ prometheus_home }}/data"
    state: directory
    mode: 0755

- name: Add Grafana
  docker_container:
    name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000  # TODO - add more config, github OAuth?
    volumes:
      - /var/lib/grafana
