---
- name: Download benchmarks
  get_url:
    url: http://hibd.cse.ohio-state.edu/download/hibd/osu-hibd-benchmarks-0.9.2.tar.gz
    dest: /home/centos/osu-hibd-benchmarks-0.9.2.tar.gz

- name: Extract benchmarks
  unarchive:
    src: /home/centos/osu-hibd-benchmarks-0.9.2.tar.gz
    dest: /home/centos/
    remote_src: yes

- name: Install maven
  package:
    name: maven
  become: true

- name: Check if already built
  stat:
    path: /home/centos/osu-hibd-benchmarks-0.9.2/spark/target/ohb-spark-0.9.2.jar
  register: ohb_bench_spark

- name: Build spark bench
  command: mvn clean package
  args:
    chdir: /home/centos/osu-hibd-benchmarks-0.9.2/spark
  when: ohb_bench_spark.stat.exists == False

- name: Start RDMA test server on slave
  command: ib_send_bw -d mlx5_0 -i 1 -F --report_gbits
  async: 30
  poll: 0  # Don't wait for it to finish
  delegate_to: "{{ groups['slave']0 }}"

- name: Run RDMA test on master
  command: "ib_send_bw -d mlx5_0 -i 1 -F --report_gbits {{ groups['slave']0 }}"

- name: Start RDMA test server on master
  command: ib_send_bw -d mlx5_0 -i 1 -F --report_gbits
  async: 30
  poll: 0  # Don't wait for it to finish

- name: Run RDMA test on slave
  command: "ib_send_bw -d mlx5_0 -i 1 -F --report_gbits {{ groups['master']0 }}"
  delegate_to: "{{ groups['slave']0 }}"

- name: Run OHB Spark benchmark
  shell: |
    export OHB_HOME=/home/centos/osu-hibd-benchmarks-0.9.2
    export SPARK_HOME=/opt/spark
    export MASTER=spark://{{ ansible_host }}:7077

    export LONG=655360
    export SHORT=65536

    $OHB_HOME/spark/ohb-run-example edu.osu.hibd.ohb.spark.SortByTest 16 $SHORT 4092 16
    $OHB_HOME/spark/ohb-run-example edu.osu.hibd.ohb.spark.GroupByTest 16 $SHORT 4092 16
