---
- name: Download OHB benchmarks
  get_url:
    url: http://hibd.cse.ohio-state.edu/download/hibd/osu-hibd-benchmarks-0.9.2.tar.gz
    dest: /home/centos/osu-hibd-benchmarks-0.9.2.tar.gz

- name: Extract OHB benchmarks
  unarchive:
    src: /home/centos/osu-hibd-benchmarks-0.9.2.tar.gz
    dest: /home/centos/
    remote_src: yes

- name: Install maven
  package:
    name: maven
  become: true

- name: Check if already built
  stat:
    path: /home/centos/osu-hibd-benchmarks-0.9.2/spark/target/ohb-spark-0.9.2.jar
  register: ohb_bench_spark

- name: Build spark bench
  command: mvn clean package
  args:
    chdir: /home/centos/osu-hibd-benchmarks-0.9.2/spark
  when: ohb_bench_spark.stat.exists == False

- name: Start RDMA test server on slave
  command: ib_send_bw -d mlx5_0 -i 1 -F --report_gbits -D 10
  async: 30
  poll: 0  # Don't wait for it to finish
  delegate_to: "{{ groups['slave'][0] }}"

- name: Run RDMA test on master
  command: "ib_send_bw -d mlx5_0 -i 1 -F --report_gbits -D 10 {{ groups['slave'][0] }}"

- name: Wait to help post test graphs
  pause:
    seconds: 10

- name: Start RDMA test server on master
  command: ib_send_bw -d mlx5_0 -i 1 -F --report_gbits -D 10
  async: 30
  poll: 0  # Don't wait for it to finish

- name: Run RDMA test on slave
  command: "ib_send_bw -d mlx5_0 -i 1 -F --report_gbits -D 10 {{ groups['master'][0]}}"
  delegate_to: "{{ groups['slave'][0] }}"

- name: Wait to help post test graphs
  pause:
    seconds: 10

- name: Run OHB Spark benchmark
  shell: |
    export SPARK_HOME=/opt/spark
    export MASTER=spark://{{ ansible_host }}:7077

    export OHB_HOME=/home/centos/osu-hibd-benchmarks-0.9.2
    export LARGE=655360
    export SMALL=120000

    $OHB_HOME/spark/ohb-run-example edu.osu.hibd.ohb.spark.SortByTest 16 $SMALL 4092 16

    sleep 10

    $OHB_HOME/spark/ohb-run-example edu.osu.hibd.ohb.spark.GroupByTest 16 $SMALL 4092 16
