---
- name: Download benchmarks
  get_url:
    url: http://hibd.cse.ohio-state.edu/download/hibd/osu-hibd-benchmarks-0.9.2.tar.gz
    dest: /home/centos/osu-hibd-benchmarks-0.9.2.tar.gz

- name: Extract benchmarks
  unarchive:
    src: /home/centos/osu-hibd-benchmarks-0.9.2.tar.gz
    dest: /home/centos/
    remote_src: yes

- name: Install maven
  package:
    name: maven
  become: true

- name: Build spark bench
  command: mvn clean package
  args:
    chdir: /home/centos/osu-hibd-benchmarks-0.9.2/spark
