---
- name: Download benchmarks
  get_url:
    url: http://hibd.cse.ohio-state.edu/download/hibd/osu-hibd-benchmarks-0.9.2.tar.gz
    dest: /home/centos/osu-hibd-benchmarks-0.9.2.tar.gz

- name: Extract benchmarks
  unarchive:
    src: /home/centos/osu-hibd-benchmarks-0.9.2.tar.gz
    dest: /home/centos/
    remote_src: yes

- name: Install maven
  package:
    name: maven
  become: true

- name: Check if already built
  stat:
    path: /home/centos/osu-hibd-benchmarks-0.9.2/spark/target/ohb-spark-0.9.2.jar
  register: ohb_bench_spark

- name: Build spark bench
  command: mvn clean package
  args:
    chdir: /home/centos/osu-hibd-benchmarks-0.9.2/spark
  when: ohb_bench_spark.stat.exists == False

- name: Run OHB Spark benchmark
  shell: |
    export OHB_HOME=/opt/spark/bench/osu-hibd-benchmarks-0.9.2/
    export SPARK_HOME=/opt/spark
    export MASTER=spark://{{ ansible_host }}:7077

    $OHB_HOME/spark/ohb-run-example edu.osu.hibd.ohb.spark.SortByTest 16 655360 4092 16
    $OHB_HOME/spark/ohb-run-example edu.osu.hibd.ohb.spark.GroupByTest 16 655360 4092 16
