---
- name: Create OpenStack config dir
  file:
    dest: /etc/openstack
    owner: root
    group: root
    state: directory

- name: Write OpenStack cloud config
  copy:
    dest: /etc/openstack/clouds.yaml
    content: "{{ openstack_conf_content }}"
    owner: root
    group: root
    mode: 0600
